### ISSUE TITLE
.NET 5 and nuget update

### ISSUE THREAD

**Issue by weedkiller** [ArazMaharramli/ShoppingApp#1]
hello I tried .NET 5 core got some errors, also with nuget updates latest... can you update... I am very interested in this.

Does it have dashboard with widgets etc

**Comment by ArazMaharramli** [comment]
hello, right now I use net core 3.1. I will update as soon as possible. thank you for your interest

> hello I tried .NET 5 core got some errors, also with nuget updates latest... can you update... I am very interested in this.
> 
> Does it have dashboard with widgets etc

**Comment by ArazMaharramli** [comment]
> hello I tried .NET 5 core got some errors, also with nuget updates latest... can you update... I am very interested in this.
> 
> Does it have dashboard with widgets etc

For projects in a solution I updated the framework to net 5.0 and NuGet packages to latest version

**Comment by weedkiller** [comment]
Hi, any chance you can put a dashboard with widgets here is nice [implementation](https://github.com/jdanylko/Tuxboard) with some charts and data tables.

Also how can we add custom roles and scaffold new views. I want to try and build a warehouse on top of this.

**Comment by ArazMaharramli** [comment]
> Hi, any chance you can put a dashboard with widgets here is nice [implementation](https://github.com/jdanylko/Tuxboard) with some charts and data tables.
> 
> Also how can we add custom roles and scaffold new views. I want to try and build a warehouse on top of this.

Hi, the app is in development stage. there are a lot of missing parts that should be developed. Also this is MVP of my e-commerce start-up project. That is why role based auth is not implemented yet.
